/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DashboardContainer_app.graphql
 * @generated SignedSource<<5f878d9872280baea52cca91df055e89>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type DashboardContainer_app = { };
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "DashboardContainer_app",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "BackgroundImagePickerContainer_app",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "DonateVcContainer_app",
      "args": null
    }
  ],
  "type": "App"
};

module.exports = fragment;
