/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DashboardContainer_user.flow
 * @generated SignedSource<<a1b2314b8e36ba2c21b308e727685325>>
 * @flow
 */

'use strict';

export type DashboardContainer_user = { };
