/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DashboardContainer_user.graphql
 * @generated SignedSource<<76b79297b476d36fe005a101732f8405>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type DashboardContainer_user = { };
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "DashboardContainer_user",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "UserDisplayContainer_user",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "UserBackgroundImageContainer_user",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "VcUserContainer_user",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "BackgroundImagePickerContainer_user",
      "args": null
    },
    {
      "kind": "FragmentSpread",
      "name": "DonateVcContainer_user",
      "args": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
