/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DashboardContainer_app.flow
 * @generated SignedSource<<22064fa626ab021e7d240e4cb92a06ac>>
 * @flow
 */

'use strict';

export type DashboardContainer_app = { };
