/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule CharitiesContainer_app.graphql
 * @generated SignedSource<<5076a3ffc8b84f1a8aa08afd3f164aea>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type CharitiesContainer_app = {
  charities?: ?CharitiesContainer_app_charities;
};

export type CharitiesContainer_app_charities_edges_node = {
  id: string;
  name?: ?string;
  category?: ?string;
};

export type CharitiesContainer_app_charities_edges = {
  node?: ?CharitiesContainer_app_charities_edges_node;
};

export type CharitiesContainer_app_charities = {
  edges?: ?Array<?CharitiesContainer_app_charities_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "CharitiesContainer_app",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "first",
          "value": 20,
          "type": "Int"
        }
      ],
      "concreteType": "CharityConnection",
      "name": "charities",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "CharityEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "Charity",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "category",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "charities{\"first\":20}"
    }
  ],
  "type": "App"
};

module.exports = fragment;
