/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule CharitiesContainer_app.flow
 * @generated SignedSource<<c5328b6ce39f435119c1dcfe1c3e553b>>
 * @flow
 */

'use strict';

export type CharitiesContainer_app = {
  charities?: ?CharitiesContainer_app_charities;
};

export type CharitiesContainer_app_charities_edges_node = {
  id: string;
  name?: ?string;
  category?: ?string;
};

export type CharitiesContainer_app_charities_edges = {
  node?: ?CharitiesContainer_app_charities_edges_node;
};

export type CharitiesContainer_app_charities = {
  edges?: ?Array<?CharitiesContainer_app_charities_edges>;
};
