/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AppContainer_viewer.flow
 * @generated SignedSource<<7286866e02a0c6ea82aa325cfa6e7920>>
 * @flow
 */

'use strict';

export type AppContainer_viewer = {
  id: string;
  username?: ?string;
};
