/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AppContainer_viewer.flow
 * @generated SignedSource<<110beeedb57cf8ad31f0e512d8e54461>>
 * @flow
 */

'use strict';

export type AppContainer_viewer = { };
