/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AppContainer_viewer.graphql
 * @generated SignedSource<<32e13d9f36b92132bc0614c1667ec064>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type AppContainer_viewer = {
  id: string;
  username?: ?string;
  email?: ?string;
  level?: ?number;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "AppContainer_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "username",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "email",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "level",
      "storageKey": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
