/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AppContainer_viewer.flow
 * @generated SignedSource<<59ef09e2a168b3ea619991875b8ac9b2>>
 * @flow
 */

'use strict';

export type AppContainer_viewer = {
  id: string;
  username?: ?string;
  email?: ?string;
  level?: ?number;
};
