/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule UserBackgroundImageContainer_user.graphql
 * @generated SignedSource<<80076df532c54cfe3a90a86b492f85c5>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type UserBackgroundImageContainer_user = {
  backgroundImage?: ?UserBackgroundImageContainer_user_backgroundImage;
};

export type UserBackgroundImageContainer_user_backgroundImage = {
  id?: ?string;
  name?: ?string;
  url?: ?string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "UserBackgroundImageContainer_user",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "Image",
      "name": "backgroundImage",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "id",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "name",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "url",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
