/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule UserDisplayContainer_user.flow
 * @generated SignedSource<<0bc70af9d08185303d2a435fd101179d>>
 * @flow
 */

'use strict';

export type UserDisplayContainer_user = {
  id: string;
  username?: ?string;
  email?: ?string;
};
