/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule UserBackgroundImageContainer_user.flow
 * @generated SignedSource<<94cfb10ccae6119f4cb904f59a8f88ed>>
 * @flow
 */

'use strict';

export type UserBackgroundImageContainer_user = {
  backgroundImage?: ?UserBackgroundImageContainer_user_backgroundImage;
};

export type UserBackgroundImageContainer_user_backgroundImage = {
  id?: ?string;
  name?: ?string;
  url?: ?string;
};
