/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule VcUserContainer_user.graphql
 * @generated SignedSource<<7981c8ed4c3e79772c236b80729fca03>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type VcUserContainer_user = {
  id: string;
  vcCurrent?: ?number;
  vcAllTime?: ?number;
  level?: ?number;
  heartsUntilNextLevel?: ?number;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "VcUserContainer_user",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "vcCurrent",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "vcAllTime",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "level",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "heartsUntilNextLevel",
      "storageKey": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
