/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule VcUserContainer_user.flow
 * @generated SignedSource<<3aa60588c8b55a12e6f309b3b39959db>>
 * @flow
 */

'use strict';

export type VcUserContainer_user = {
  id: string;
  vcCurrent?: ?number;
  vcAllTime?: ?number;
  level?: ?number;
  heartsUntilNextLevel?: ?number;
};
