/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule BackgroundImagePickerContainer_app.graphql
 * @generated SignedSource<<6d8f781e2c8fcf0af53da8e930ed2722>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type BackgroundImagePickerContainer_app = {
  backgroundImages?: ?BackgroundImagePickerContainer_app_backgroundImages;
};

export type BackgroundImagePickerContainer_app_backgroundImages_edges_node = {
  id: string;
  name?: ?string;
  url?: ?string;
};

export type BackgroundImagePickerContainer_app_backgroundImages_edges = {
  node?: ?BackgroundImagePickerContainer_app_backgroundImages_edges_node;
};

export type BackgroundImagePickerContainer_app_backgroundImages = {
  edges?: ?Array<?BackgroundImagePickerContainer_app_backgroundImages_edges>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "BackgroundImagePickerContainer_app",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "first",
          "value": 20,
          "type": "Int"
        }
      ],
      "concreteType": "BackgroundImageConnection",
      "name": "backgroundImages",
      "plural": false,
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "args": null,
          "concreteType": "BackgroundImageEdge",
          "name": "edges",
          "plural": true,
          "selections": [
            {
              "kind": "LinkedField",
              "alias": null,
              "args": null,
              "concreteType": "BackgroundImage",
              "name": "node",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "id",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "name",
                  "storageKey": null
                },
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "args": null,
                  "name": "url",
                  "storageKey": null
                }
              ],
              "storageKey": null
            }
          ],
          "storageKey": null
        }
      ],
      "storageKey": "backgroundImages{\"first\":20}"
    }
  ],
  "type": "App"
};

module.exports = fragment;
