/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule BackgroundImagePickerContainer_app.flow
 * @generated SignedSource<<4e12e14e34da8e18a74965c75e5acbfe>>
 * @flow
 */

'use strict';

export type BackgroundImagePickerContainer_app = {
  backgroundImages?: ?BackgroundImagePickerContainer_app_backgroundImages;
};

export type BackgroundImagePickerContainer_app_backgroundImages_edges_node = {
  id: string;
  name?: ?string;
  url?: ?string;
};

export type BackgroundImagePickerContainer_app_backgroundImages_edges = {
  node?: ?BackgroundImagePickerContainer_app_backgroundImages_edges_node;
};

export type BackgroundImagePickerContainer_app_backgroundImages = {
  edges?: ?Array<?BackgroundImagePickerContainer_app_backgroundImages_edges>;
};
