/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule BackgroundImagePickerContainer_user.graphql
 * @generated SignedSource<<8a3860ebf8b22b4238454fd356cd2513>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type BackgroundImagePickerContainer_user = {
  id: string;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "BackgroundImagePickerContainer_user",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
