/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule BackgroundImagePickerContainer_user.flow
 * @generated SignedSource<<e3f59954b8c9b982be45e909d21129f2>>
 * @flow
 */

'use strict';

export type BackgroundImagePickerContainer_user = {
  id: string;
};
