// Add the modules that we use in client JS.
// These will be bundled into vendor.js, so that our vendor JS
// filename hash will not change when we modify app code.
require('firebase')
require('hex-to-rgba')
require('lodash')
require('material-ui')
require('material-ui-next')
require('moment')
require('object-assign')
require('prop-types')
require('promise')
require('react')
require('react-color')
require('react-custom-scrollbars')
require('react-dom')
require('react-firebaseui')
require('react-ga')
require('react-hot-loader')
require('react-intl')
require('react-measure')
require('react-relay')
require('react-router')
require('react-tap-event-plugin')
require('react-transition-group')
require('whatwg-fetch')
require('xregexp')
