/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DonateVcContainer_app.flow
 * @generated SignedSource<<9ea690b6f54046b8aae0faafb84e5f45>>
 * @flow
 */

'use strict';

export type DonateVcContainer_app = {
  charities?: ?DonateVcContainer_app_charities;
};

export type DonateVcContainer_app_charities_edges_node = {
  id: string;
  name?: ?string;
  category?: ?string;
};

export type DonateVcContainer_app_charities_edges = {
  node?: ?DonateVcContainer_app_charities_edges_node;
};

export type DonateVcContainer_app_charities = {
  edges?: ?Array<?DonateVcContainer_app_charities_edges>;
};
