/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DonateVcContainer_user.flow
 * @generated SignedSource<<fd893eb337a40be39f7441265d2b9951>>
 * @flow
 */

'use strict';

export type DonateVcContainer_user = {
  id: string;
  vcCurrent?: ?number;
};
