/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DonateVcContainer_user.graphql
 * @generated SignedSource<<aded22ba60cc0f4a62739d28841e4bb0>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type DonateVcContainer_user = {
  id: string;
  vcCurrent?: ?number;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "DonateVcContainer_user",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "vcCurrent",
      "storageKey": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
